[package]
name = "ferris_chats_server"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.8.1"
axum-server = "0.7.1"
tokio = { version = "1.43.0", features = ["rt-multi-thread"] }
chrono = "0.4.39"
ctrlc = "3.4.5"
ferris_chats_data = "*"
